name: Laravel Pint

on:
  push:
    branches:
      - feature/*

jobs:
  pint:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          php-version: 8.3
          php-extensions: 'json, dom, curl, libxml, mbstring'

      - name: Install deps
        run: composer install --no-progress --no-interaction

      - name: Run Pint
        run: vendor/bin/pint --test
