name: Laravel Pint

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  pint:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run Pint
        run: vendor/bin/pint --test
