name: PHPUnit

on:
  pull_request

jobs:
  tests:
    runs-on: ubuntu-22.04

    services:
      mysql:
        image: mysql:9.2.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: forum
          MYSQL_ALLOW_EMPTY_PASSWORD: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          php-version: '8.3'

      - name: Install Deps
        run: composer install -q --no-progress --no-interaction

      - name: Prepare application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run Tests
        run: php artisan test --compact --parallel
